Website/Models/News.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Website.Models
{
    public class News
    {
        public int Id { get; set; }
        public string Title { get; set; } // Название и текст новости
        public string Images { get; set; } // Картинка 
        public string Organization { get; set; }
        public string Position { get; set; }
        public string Name { get; set; } // Фио ответственого
        public DateTime DateStart { get; set; } // Дата начало проведения
        public DateTime DateFinish { get; set; } // Дата конца проведения
        public string Language { get; set; }
        public string DayWeek { get; set; } // для красивого вывода по дням. Надо переделать!!!! 
    }
}

Website/Models/NewsTable.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Website.Models
{
    public class NewsTable
    {
        public int Id { get; set; }
        public string DateTime { get; set; } // Дата новостей
        public string Name { get; set; } // Название новости
        public string Executor { get; set; } // Исполнитель
    }
}

Website/Models/WebSiteBD/News.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Website.Models.WebSiteBD
{
    /*Модель предназначена для вывода текущих новостей из базы WebSiteBD*/
    public class News
    {
        public int Id { get; set; }
        public string Title { get; set; } // Название и текст новости
        public string Organization { get; set; }
        public string Position { get; set; }
        public string Name { get; set; } // Фио ответственого
        public DateTime DateStart { get; set; } // Дата начало проведения
        public DateTime DateFinish { get; set; } // Дата конца проведения
        public string Language { get; set; }
    }
}

Website/Models/WebSiteBD/NewsTable.cs
using System.ComponentModel.DataAnnotations;
using System.Data;
using Website.Interfaces.LoadXLSX;

namespace Website.Models.WebSiteBD
{
    /*Модель предназначена для вывода новостей за месяц из базы WebSiteBD*/
    public class NewsTable : IDataForNewsTable
    {
        public int Id { get; set; }
        public string DateTime { get; set; } // Дата новостей
        public string Name { get; set; } // Название новости
        public string Executor { get; set; } // Исполнитель

        public NewsTable()
        {
        }
        public NewsTable(string _a, string _b, string _c)
        {
            DateTime = _a;
            Name = _b;
            Executor = _c;
        }

        public NewsTable(DataRow item)
        {
            DateTime = item["MyFieldA"].ToString();
            Name = item["MyFieldB"].ToString();
            Executor = item["MyFieldC"].ToString();
        }
    }
}

Website/Controllers/AddNewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Website.Assistant.LoadXLSX;
using Website.Models.Context;
using Website.Models.WebSiteBD;
using Website.Models.WebSiteBD.LoadXLSX;

namespace Website.Controllers
{
    public class AddNewsController : Controller
    {
        public IActionResult Index()
        {
            using (Context _dbNews = new Context())
            {
                var news = _dbNews.News.Where(d => d.DateStart.Month >= DateTime.Now.Month).Where(f => f.DateStart.Month <= DateTime.Now.Month + 1).OrderBy(t => t.DateStart).ToList();
                return View(news);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new News());
        }

        public ViewResult Edit(int Id)
        {
            using (Context _dbNews = new Context())
            {
                News news = _dbNews.News
            .FirstOrDefault(g => g.Id == Id);
                return View(news);
            }
        }

        [HttpPost]
        public ActionResult Edit(News news)
        {
            if (ModelState.IsValid)
            {
                Save(news);
                TempData["message"] = string.Format("Изменения в новости \"{0}\" были сохранены", news.Title);
                return Redirect("Index");
            }
            else
            {
                // Что-то не так со значениями данных
                return View(news);
            }
        }

        public void Save(News news)
        {
            using (Context _dbNews = new Context())
            {
                if (news.Id == 0)
                    _dbNews.Add(news);
            else
            {
                News dbEntry = _dbNews.News.Find(news.Id);
                if (dbEntry != null)
                {
                    dbEntry.Title = news.Title;
                    dbEntry.Name = news.Name;
                    dbEntry.Organization = news.Organization;
                    dbEntry.Position = news.Position;
                    dbEntry.DateStart = news.DateStart;
                    dbEntry.DateFinish = news.DateFinish;
                    dbEntry.Language = news.Language;
                }
            }
                _dbNews.SaveChanges();
            }
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            News deleted = DeleteNews(Id);
            if (deleted != null)
            {
                TempData["message"] = string.Format("Новость \"{0}\" была удалена",
                    deleted.Title);
            }
            return Redirect("Index");
        }

        public News DeleteNews(int Id)
        {
            using (Context _dbNews = new Context())
            {
                News dbEntry = _dbNews.News.Find(Id);
                if (dbEntry != null)
                {
                    _dbNews.News.Remove(dbEntry);
                    _dbNews.SaveChanges();
                }
                return dbEntry;
            }
        }


        int week = DateTime.Now.Month;
        public IActionResult NewsTable()
        {
            using (Context _dbNews = new Context())
            {
                var news = _dbNews.NewsTable.Where(p => Convert.ToDateTime(p.DateTime.Substring(0, 9)).Month == week).OrderBy(d => d.DateTime).ToList();
                return View(news);
            }
        }

        public ViewResult CreateTable()
        {
            return View("EditTable", new NewsTable());
        }

        public ViewResult EditTable(int Id)
        {
            using (Context _dbNews = new Context())
            {
                NewsTable news = _dbNews.NewsTable
            .FirstOrDefault(g => g.Id == Id);
            return View(news);
            }
        }

        [HttpPost]
        public ActionResult EditTable(NewsTable news)
        {
            if (ModelState.IsValid)
            {
                Save(news);
                TempData["message"] = string.Format("Изменения в новости \"{0}\" были сохранены", news.Name);
                return Redirect("NewsTable");
            }
            else
            {
                // Что-то не так со значениями данных
                return View(news);
            }
        }

        public void Save(NewsTable news)
        {
            using (Context _dbNews = new Context())
            {
                if (news.Id == 0)
                    _dbNews.Add(news);
                else
                {
                    NewsTable dbEntry = _dbNews.NewsTable.Find(news.Id);
                    if (dbEntry != null)
                    {
                        dbEntry.DateTime = news.DateTime;
                        dbEntry.Name = news.Name;
                        dbEntry.Executor = news.Executor;
                    }
                }
                _dbNews.SaveChanges();
            }
        }

        [HttpPost]
        public ActionResult DeleteTable(int Id)
        {
            NewsTable deleted = DeleteNewsTable(Id);
            if (deleted != null)
            {
                TempData["message"] = string.Format("Новость \"{0}\" была удалена",
                    deleted.Name);
            }
            return Redirect("NewsTable");
        }

        public NewsTable DeleteNewsTable(int Id)
        {
            using (Context _dbNews = new Context())
            {
                NewsTable dbEntry = _dbNews.NewsTable.Find(Id);
                if (dbEntry != null)
                {
                    _dbNews.NewsTable.Remove(dbEntry);
                    _dbNews.SaveChanges();
                }
                return dbEntry;
            }
        }


        public ActionResult SaveNewsTable()
        {
            var dt = new LoadEcxel().ReadFile("/app/wwwroot/loading/ReadMePlease.xlsx");
            var myDataFromExcel = new List<NewsTable>();
            //Заполняем наш объект, считанными данными из DataTable
            foreach (DataRow item in dt.Rows)
            {
                if (item.ItemArray[0].ToString() != "") 
                {
                    myDataFromExcel.Add(new NewsTable(item));
                }
            }

            foreach (var item in myDataFromExcel)
            {
                using (Context _dbNews = new Context())
                {
                    _dbNews.Add(item);
                    _dbNews.SaveChanges();
                }
            }
            return Redirect("NewsTable");
        }

    }
}

Website/Views/AddNews/Edit.cshtml
@model Website.Models.WebSiteBD.News

@{
    ViewData["Title"] = "Edit";
}

<section id="news" style="padding: 80px 15px 80px 15px;">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h4>Новости</h4>
                <hr />
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label">Тема</label>
                        @Html.TextAreaFor(x => x.Title, new { @id="title", @class = "form-control", @required = "required", @style = "min-width: 100%; width: 100%; max-width: 100%; min-height: 60px" })
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label">Исполнитель</label>
                        @Html.TextAreaFor(x => x.Name, new { @id="nameOrg", @class = "form-control", @required = "required", @style = "min-width: 100%; width: 100%; max-width: 100%; min-height: 60px" })
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateStart" class="control-label">Дата начало</label>
                        <input asp-for="DateStart" class="form-control" id="date" />
                        <span asp-validation-for="DateStart" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateFinish" class="control-label">Дата конец</label>
                        <input asp-for="DateFinish" class="form-control" id="date2" />
                        <span asp-validation-for="DateFinish" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Position" class="control-label">Должность представителя</label>
                        @Html.TextAreaFor(x => x.Position, new { @id="position", @class = "form-control", @required = "required", @style = "min-width: 100%; width: 100%; max-width: 100%; min-height: 60px" })
                        <span asp-validation-for="Position" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Organization" class="control-label">Представитель исполнителя</label>
                        @Html.TextAreaFor(x => x.Organization, new {  @id="organization", @class = "form-control", @required = "required", @style = "min-width: 100%; width: 100%; max-width: 100%; min-height: 60px" })
                        <span asp-validation-for="Organization" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Language" class="control-label">Язык новостей</label>
                        @Html.DropDownListFor(x => x.Language, new SelectList(new string[] { "ru", "be" }), new { @class = "form-control" })
                        <span asp-validation-for="Language" class="text-danger"></span>
                    </div>
                    <div class="panel-footer">
                        <input type="submit" value="Сохранить" class="btn btn-primary" />
                        @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new { @class = "btn btn-default" })
                    </div>
                </form>
            </div>
            <div class="col-md-4">
                <div class="post-date"> <h4 style="color:white; margin: 0px">Понедельник</h4>  <h6 style="text-align:right; color:white; margin: 0px"> 01/03/2020</h6></div>
                <br />
                <div class="box">
                    <div class="icon"><a href=""><i class="fa fa-forumbee"></i></a></div>
                    <h6 style="text-align:right; margin: 10px">9:00 - 12:00</h6>
                    <h4 class="title" > <b>Тема:</b> <text id="resultTitle">Порядок изменения целевого назначения земельных участков</text> </h4>
                    <p class="description" style="margin: 20px 0px 0px 0px">
                        Исполнитель:  <text id="resultName">Комитет землеустройства Мингорисполкома</text>
                        <br /> <br />
                        <b> Представитель исполнителя - </b>  <text id="resultPosition">Заместитель начальника управления организации земельных отношений комитета землеустройства Минского городского исполнительного комитета</text>
                        <br />
                        <b id="resultOrganization">Иберзова Екатерина Владимировна</b>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    if ($('#date').val() == $('#date2').val()) {
        $('#date').val(moment().format("YYYY-MM-DDT09:00"));
        $('#date2').val(moment().format("YYYY-MM-DDT12:00"));
    } else { }

  function showCount() {
      resultTitle.innerHTML = title.value;
      resultName.innerHTML = nameOrg.value;
      resultPosition.innerHTML = position.value;
      resultOrganization.innerHTML = organization.value;
  }

  title.onkeyup = title.oninput = showCount;
  title.onpropertychange = function() {
    if (event.propertyName == "value") showCount();
  }
  title.oncut = function() {
    setTimeout(showCount, 0); // на момент oncut значение ещё старое
  };
 
  nameOrg.onkeyup = nameOrg.oninput = showCount;
  nameOrg.onpropertychange = function() {
    if (event.propertyName == "value") showCount();
  }
  nameOrg.oncut = function() {
    setTimeout(showCount, 0); // на момент oncut значение ещё старое
    }; 

  position.onkeyup = position.oninput = showCount;
  position.onpropertychange = function() {
    if (event.propertyName == "value") showCount();
  }
  position.oncut = function() {
    setTimeout(showCount, 0); // на момент oncut значение ещё старое
    }; 

  organization.onkeyup = organization.oninput = showCount;
  organization.onpropertychange = function() {
    if (event.propertyName == "value") showCount();
  }
  organization.oncut = function() {
    setTimeout(showCount, 0); // на момент oncut значение ещё старое
  };

</script>

Website/Views/AddNews/EditTable.cshtml
@model Website.Models.WebSiteBD.NewsTable

@{
    ViewData["Title"] = "EditTable";
}
<section id="news" style="padding: 80px 15px 80px 15px;">
    <div class="container">
        <div class="col-md-12">
            <h4>График новостей</h4>
            <hr />
            <form asp-action="EditTable">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="DateTime" class="control-label">Дата, время проведения</label>
                    @Html.TextAreaFor(x => x.DateTime, new { @id = "dateTime", @class = "form-control", @required = "required", @style = "min-width: 100%; width: 100%; max-width: 100%; min-height: 60px" })
                    <span asp-validation-for="DateTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Тема дня информирования</label>
                    @Html.TextAreaFor(x => x.Name, new { @class = "form-control", @required = "required", @style = "min-width: 100%; width: 100%; max-width: 100%; min-height: 60px;" })
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Executor" class="control-label">Ответственный исполнитель</label>
                    @Html.TextAreaFor(x => x.Executor, new { @class = "form-control;", @required = "required", @style = "min-width: 100%; width: 100%; max-width: 100%; min-height: 60px;" })
                    <span asp-validation-for="Executor" class="text-danger"></span>
                </div>
                <div class="panel-footer">
                    <input type="submit" value="Сохранить" class="btn btn-primary" />
                    @Html.ActionLink("Вернуться к списку", "NewsTable", null, new { @class = "btn btn-default" })
                </div>
            </form>
        </div>
    </div>
</section>

<script>
    $(function(){
        $("#dateTime").mask("99.99.9999 99.99-99.99");
});

</script>

Website/Views/AddNews/Index.cshtml
@model IEnumerable<Website.Models.WebSiteBD.News>

@{
     ViewData["Title"] = "Index";
}
    <div class="text-center" style="        padding: 80px 15px 80px 15px;">
        <h1 class="display-4">Новости</h1>
        <a asp-controller="AddNews" asp-action="NewsTable">График проведения тематических дней информирования</a>
        <br /><br />

        <p>
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#multiCollapseExample1" aria-expanded="false" aria-controls="multiCollapseExample1">Список новостей за месяц</button>
        </p>
        @TempData["message"]
        <div class="row">
            <div class="col">
                <div class="collapse multi-collapse" id="multiCollapseExample1">
                    <div class="card card-body">
                        <table id="tablePreview" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Тема</th>
                                    <th>Исполнитель</th>
                                    <th>Дата начало</th>
                                    <th>Дата конец</th>
                                    <th>Должность представителя</th>
                                    <th>Представитель исполнителя</th>
                                    <th>Язык новостей</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var news in Model)
                                {
                                    <tr>
                                        <td>@Html.ActionLink(news.Title, "Edit", new { news.Id })</td>
                                        <td>@news.Name</td>
                                        <td>@news.DateStart</td>
                                        <td>@news.DateFinish</td>
                                        <td>@news.Position</td>
                                        <td>@news.Organization</td>
                                        <td>@news.Language</td>
                                        <td>
                                            @using (Html.BeginForm("Delete", "AddNews"))
                                            {
                                                @Html.Hidden("Id", news.Id)
                                                <input type="submit"
                                                       class="btn btn-danger btn-xs"
                                                       value="Удалить" />
                                            }
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Добавить новость", "Create", null,
                new { @class = "btn btn-default" })
        </div>
    </div>

Website/Views/AddNews/NewsTable.cshtml
@model IEnumerable<Website.Models.WebSiteBD.NewsTable>

@{
    ViewData["Title"] = "News table";
}
<div class="text-center" style="        padding: 80px 15px 80px 15px;">
    <h1 class="display-4">
        График проведения
        тематических дней
        информирования
    </h1>
    <a asp-controller="AddNews" asp-action="Index">Новости</a><br /><br />
    @TempData["message"]
    <div>
        <table id="tablePreview" class="table table-striped">
            <thead>
                <tr>
                    <th>Дата, время проведения</th>
                    <th>Тема дня информирования</th>
                    <th>Ответственный исполнитель</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var news in Model)
                {
                    <tr>
                        <td>@news.DateTime</td>
                        <td>@Html.ActionLink(news.Name, "EditTable", new { news.Id })</td>
                        <td>@news.Executor</td>
                        <td>
                            @using (Html.BeginForm("DeleteTable", "AddNews"))
                            {
                                @Html.Hidden("Id", news.Id)
                                <input type="submit"
                                       class="btn btn-danger btn-xs"
                                       value="Удалить" />
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
    <div class="panel-footer">
        @Html.ActionLink("Добавить новость", "CreateTable", null,
            new { @class = "btn btn-default" })
        <br />   <br />
        @using (Html.BeginForm("SaveNewsTable", "AddNews", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <button type="submit" class="btn btn-primary">Загрузить файл</button>
        }
    </div>
</div>