Website/Controllers/HelpInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Website.Models.Context;
using Website.Models.OneWin;

namespace Website.Controllers
{
    [Route("information")]
    public class HelpInformationController : Controller
    {
        /*
         * Для вывода всей инфы справочной системы используется несколько хранимых процедур:
         * 1.ProceduresList - выводит название перечней, глав, процедур.
         * 2.При нажатии на выбраную процедуру в хранимы процедуры передается ID-процедуры и выводятся данные для данной процедуры. 
         */
        [Route("index")]
        public IActionResult Index()
        {
            return View();
        }

        string _area;
        void Area(string area)
        {
            switch (area)
            {
                case "Заводской район":
                    _area = "onewin_zav_db";
                    break;
                case "Ленинский район":
                    _area = "onewin_len_db";
                    break;
                case "Московский район":
                    _area = "onewin_mos_db";
                    break;
                case "Октябрьский район":
                    _area = "onewin_okt_db";
                    break;
                case "Партизанский район":
                    _area = "onewin_par_db";
                    break;
                case "Первомайский район":
                    _area = "onewin_per_db";
                    break;
                case "Советский район":
                    _area = "onewin_sov_db";
                    break;
                case "Фрунзенcкий район":
                    _area = "onewin_frun_db"; 
                    break;
                case "Центральный район":
                    _area = "onewin_cen_db";
                    break;
                case "Мингорисполком":
                    _area = "onewin_mingor_db";
                    break;
                default:
                    _area = "onewin_mingor_db";
                    break;
            }
        }

        public FileResult Download(string path, string area)
        {
            Area(area);
            var doc = new byte[0];
            doc = System.IO.File.ReadAllBytes("/app/wwwroot/temp_site/" + _area + '/' + path);
            return File(doc, " application/vnd.openxmlformats-officedocument.wordprocessingml.document", path);
        }

        [HttpPost]
        [Route("index")]
        public IActionResult Index(string area, int check)
        {
            Area(area);
            using (Context _db = new Context())
            {
                List<ProceduresList> registrations = _db.ProceduresLists.FromSql("EXECUTE dbo.ProceduresLists @nameDB = {0}, @IP = {1}", _area, check).ToList();
                return View(registrations);
            }
        }

        /// <summary>
        /// Функция получает от Ajax метода данные для создания запросов в SQL, для получения информации о процедуре не обнавляя View
        /// </summary>
        /// <param name="person">данные о человеке и его обращение</param>
        /// <returns></returns>
        [Route("docregistry")]
        public JsonResult DocRegistry(string id, string area)
        {
            Area(area);
            using (Context _db = new Context())
            {
                ListRegistry listRegistry = new ListRegistry
                {
                    Registries = _db.Registry.FromSql("EXECUTE dbo.Registry @id = {0},  @nameDB = {1}", id, _area).ToList(),
                    NormativeDocs = _db.NormativeDoc.FromSql("EXECUTE dbo.NormativeDoc @id = {0},  @nameDB = {1}", id, _area).OrderBy(i=>i.Name).ToList(),
                    Documents = _db.Document.FromSql("EXECUTE dbo.Docs @id = {0},  @nameDB = {1}", id, _area).OrderBy(i=>i.Name).ToList(),
                    RequestedDocuments = _db.RequestedDocuments.FromSql("EXECUTE dbo.ZaprDocs @id = {0},  @nameDB = {1}", id, _area).OrderBy(i=>i.Name).ToList(),
                    Performers = _db.Performers.FromSql("EXECUTE dbo.Performers @id = {0},  @nameDB = {1}", id, _area).ToList(),
                    Departaments = _db.Departaments.FromSql("EXECUTE dbo.Departments @id = {0},  @nameDB = {1}", id, _area).ToList(),
                    Executor = _db.Performers.FromSql("EXECUTE dbo.Executor @id = {0},  @nameDB = {1}", id, _area).ToList(),
                    PaymentAccaount = _db.PaumentAccaounts.FromSql("EXECUTE dbo.PaymentAccount @id = {0},  @nameDB = {1}", id, _area).ToList(),
                    DepartamentsAccept = _db.Departaments.FromSql("EXECUTE dbo.DepartmentsAccept @id = {0},  @nameDB = {1}", id, _area).ToList(),
                    DocumentAccept = _db.Performers.FromSql("EXECUTE dbo.DocumentAccept @id = {0},  @nameDB = {1}", id, _area).ToList(),
                    CommentDepartaments = _db.CommentDepartaments.FromSql("EXECUTE CommentDepartaments  @id = {0}, @nameDB = {1}", id, _area).ToList()
                };

                return new JsonResult(listRegistry);
            }
        }

        [Route("unique")]
        public IActionResult UniqueId()
        {
            return View();
        }



        [Route("admprocedure")]
        public IActionResult AdmProcedure()
        {
            return View();
        }

        [Route("webcamers")]
        public IActionResult WebCamers()
        {
            return View();
        }
    }
}

Website/Views/Shared/_Layout.cshtml
 @using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mgaon.by</title>
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/sectionViewsHomeNew_ver=1.css" type="text/css" />
    <link rel="stylesheet" href="~/css/siteNew_ver=1.css" type="text/css" />
    <script src="jquery.tools.mins.js" type="text/javascript"></script>
    <!-- ссылка на Moment.js library -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js" type="text/javascript"></script>
    <!--Ajax-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (m, e, t, r, i, k, a) {
        m[i] = m[i] || function () { (m[i].a = m[i].a || []).push(arguments) };
            m[i].l = 1 * new Date(); k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
        })
            (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(61600912, "init", {
            clickmap: true,
            trackLinks: true,
            accurateTrackBounce: true
        });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/61600912" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</head>

<body>
    <!--Header Section-->
    <header id="header" class="header-fixed">
        <div class="container">

            <div class="row">
                <!--Button Visually Impaired-->
                <div>
                    <button id="specialButton" class="navbar-eye" href="#">
                        <span class="fa fa-low-vision"></span>
                    </button>
                </div>

                <div id="logo">
                    <h1>
                        <a asp-controller="Home" asp-action="Index">@Localizer["Title"]</a>
                    </h1>
                </div>

                <!--Button Menu-->
                <button id="navbar-togglers" class="navbar-togglers" onclick="openNav()"> <span class="fa fa-bars"></span> </button>

                <div class="SelectLanguage"> <span> @await Html.PartialAsync("_SelectLanguagePartial")</span> </div>

                <!--Search Section-->
                <div class="navbar-search" data-bem="{&quot;action&quot;:&quot;https://yandex.ru/search/site/&quot;,&quot;arrow&quot;:true,&quot;bg&quot;:&quot;#ffffff&quot;,&quot;fontsize&quot;:16,&quot;fg&quot;:&quot;#000000&quot;,&quot;language&quot;:&quot;ru&quot;,&quot;logo&quot;:&quot;rb&quot;,&quot;publicname&quot;:&quot;Mgaon.by&quot;,&quot;suggest&quot;:true,&quot;target&quot;:&quot;_self&quot;,&quot;tld&quot;:&quot;ru&quot;,&quot;usebigdictionary&quot;:true,&quot;searchid&quot;:2373846,&quot;input_fg&quot;:&quot;#000000&quot;,&quot;input_bg&quot;:&quot;#ffffff&quot;,&quot;input_fontStyle&quot;:&quot;normal&quot;,&quot;input_fontWeight&quot;:&quot;normal&quot;,&quot;input_placeholder&quot;:&quot;&quot;,&quot;input_placeholderColor&quot;:&quot;#000000&quot;,&quot;input_borderColor&quot;:&quot;#ffffff&quot;}">
                    <form action="https://yandex.ru/search/site/" method="get" target="_self" accept-charset="utf-8">
                        <input type="hidden" name="searchid" value="2373846" />
                        <input type="hidden" name="l10n" value="ru" />
                        <input type="hidden" name="reqenc" value="" />
                        <input type="search" name="text" value="" style="border-radius: 10px; border:0" />
                        <button type="submit" style="color: #fff; font-size: 20px; cursor: pointer; border:0; background-color: rgba(52, 59, 64, 0.0); transition: background 0.5s; border-radius: 10px;">
                            <span class="fa fa-search"></span>
                        </button>
                    </form>
                </div>

                <style type="text/css">
                    .ya-page_js_yes .ya-site-form_inited_no {
                        display: none;
                    }
                </style>
            </div>

            <!--navbar-->
            <div id="myNav" class="overlay">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span class="fa fa-bars"></span></a>

                <div class="overlay-content row">
                    <div class="col-sm-4 container text-center">
                        <br>
                        <h4 style="color: #f7f7f7;">@Localizer["Enterprise"]</h4>
                        <a asp-controller="Home" asp-action="Index" asp-fragment="about" onclick="closeNav()">@Localizer["About"]</a> <br />
                        <a asp-controller="Home" asp-action="Index" asp-fragment="area" onclick="closeNav()">@Localizer["Department"]</a> <br />
                        <a asp-controller="Home" asp-action="Index" asp-fragment="call-to-action" onclick="closeNav()">@Localizer["CallCenter"]</a> <br />
                        <a asp-controller="Home" asp-action="Index" asp-fragment="news" onclick="closeNav()">@Localizer["News"]</a> <br />
                        <a asp-controller="Home" asp-action="Index" asp-fragment="trade-union-organization" onclick="closeNav()">@Localizer["Union"]</a> <br />
                        <a asp-controller="Home" asp-action="Index" asp-fragment="contact" onclick="closeNav()">@Localizer["Сontact"]</a>
                    </div>

                    <div class="col-sm-4 container text-center">
                        <br>
                        <h4 style="color: #f7f7f7;">@Localizer["Service"]</h4>
                        <a href="http://prereg.mgaon.by" onclick="closeNav()">@Localizer["PreliminaryRecord"]</a><br />
                        <a asp-controller="Service" asp-action="Information" onclick="closeNav()">@Localizer["InformationAboutPassingDocuments"]</a>
                        <a asp-controller="Service" asp-action="Index" onclick="closeNav()">@Localizer["Appeal"]</a><br />
                        <a href="https://docs.google.com/forms/d/e/1FAIpQLSfx5Ny-YbLxyEZvU3E4_dmmpFLWesSv_7_WORTUwGdtHd7uRA/viewform?c=0&w=1" onclick="closeNav()">@Localizer["Questionnaire"]</a><br />
                    </div>

                    <div class="col-sm-4 container text-center">
                        <br>
                        <h4 style="color: #f7f7f7;">@Localizer["ReferenceInformation"]</h4>
                        <a asp-controller="HelpInformation" asp-action="Index">@Localizer["ReferenceInformationSystem"]</a><br />
                        <a asp-controller="HelpInformation" asp-action="AdmProcedure">@Localizer["Legislation"]</a><br />
                        <a asp-controller="HelpInformation" asp-action="UniqueId">@Localizer["ElectroniDigitalSignature"]</a>
                        <a asp-controller="HelpInformation" asp-action="WebCamers">@Localizer["WebCamers"]</a><br />
                        <br>
                    </div>
                </div>
            </div>

        </div>
    </header>
    <!--End Header Section-->
    <!--Main Section-->
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <!-- End Main Section-->
    <!--Footer Section-->
    <footer id="footer">
        <div class="footer-top">
            <div class="container text-center">
                на сайте использован материал «Minsk - 2019 – Минск» из видеохостинга YouTube автора <strong>BlinkovFPV</strong>
            </div>
        </div>


        <div class="copyright">
            <!-- Yandex.Metrika informer -->
            <a href="https://metrika.yandex.ru/stat/?id=61600912&amp;from=informer"
               target="_blank" rel="nofollow">
                <img src="https://informer.yandex.ru/informer/61600912/1_0_343B40FF_343B40FF_1_pageviews"
                     style="width:80px; height:15px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры)" class="ym-advanced-informer" data-cid="61600912" data-lang="ru" />
            </a>
            <!-- /Yandex.Metrika informer -->
        </div>
    </footer>
    <!--End Footer Section-->

    <script>
        function openNav() {
            document.getElementById("myNav").style.width = "100%";
            document.getElementById("navbar-togglers").style.display = "none";
        }

        function closeNav() {
            document.getElementById("myNav").style.width = "0%";
            document.getElementById("navbar-togglers").style.display = "inline";
        }
    </script>


    <environment include="Staging,Production">
        <!--Для яндекс поиск-->
        <script type="text/javascript">
            (function (w, d, c) {
                var s = d.createElement('script'), h = d.getElementsByTagName('script')[0], e = d.documentElement;
                if ((' ' + e.className + ' ').indexOf(' ya-page_js_yes ') === -1) {
                    e.className += ' ya-page_js_yes';
                }
                s.type = 'text/javascript'; s.async = true; s.charset = 'utf-8';
                s.src = (d.location.protocol === 'https:' ? 'https:' : 'http:') + '//site.yandex.net/v2.0/js/all.js';
                h.parentNode.insertBefore(s, h); (w[c] || (w[c] = [])).push(function () { Ya.Site.Form.init() })
            }
            )
                (window, document, 'yandex_site_callbacks');
        </script>

        <!--Живосайт-->
        <script type='text/javascript'>
            (function () {
                var widget_id = 'cG109CXkFy'; var d = document; var w = window; function l() {
                    var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true;
                    s.src = '//code.jivosite.com/script/widget/' + widget_id
                        ; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);
                }
                if (d.readyState == 'complete') { l(); } else {
                    if (w.attachEvent) { w.attachEvent('onload', l); }
                    else { w.addEventListener('load', l, false); }
                }
            })();
        </script>

        <!--Для слобовидящих-->
        <script src="https://lidrekon.ru/slep/js/jquery.js"></script>
        <script src="https://lidrekon.ru/slep/js/uhpv-full.min.js"></script>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/jquery-masked/jquery.maskedinput.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script type="text/javascript" charset="windows-1251" src="~/js/main.js"></script>
    </environment>
</body>

</html>

Website/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
.Select(c => new SelectListItem { Value = c.Name, Text = c.EnglishName })
.ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:5px;"
            asp-route-returnUrl="@Context.Request.Path"
            method="post" class="form-horizontal SelectLanguage">
    <div class="styled-select select">
        <select class="SelectLanguage" name="culture" onchange="this.form.submit();"
                                                    asp-for="@requestCulture.RequestCulture.UICulture.Name"
                                                    asp-items="cultureItems"></select>
    </div>
</form>